export const randomResponses = [
    "Ok",
    "YEP",
    "Stare",
    "Concerned u sure?",
    "Concerned i mean...",
    "CAUGHTIN4K",
    "LOser keep talking buddy",
    "NOPERS i dont think so",
    "NODDERS damn right",
    "Ok good enough",
    "Lmao look at this guy KEKW",
    "Talking keep talking",
    "Wow",
    "NOTED uh huh",
    "Plotge",
    "Susge hmmm",
    "owojam dance with me owojam",
    "you're so right",
    "Damn bro Wow",
    "Imagine doing that, wouldnt be me Clueless",
    "Hmm interesting",
    "owo you called?",
    "owoshy im here",
    "pepePoint look at this guy",
    "Chatting keep typing bud",
    "HUH uhhhh",
    "Shruge idk man",
    "COPIUM good stuff",
    "Aware oh...",
    "COPIUM if you say so...",
    "weSmart smart",
    "fricc you",
    "KEKW Sez u",
    "Concerned You called?",
    "What you gonna do about it Stare",
    "HUH",
    "I kinda agree with that",
    "idk, you tell me buddy KEKW",
    "I guess you're right FeelsBadMan",
    "NotCrying im sorry",
    "I Dont wanna talk about it Stare",
    "monkaW i dont think we should talk about it",
    "Yeah.... lets not NOPERS",
    "Did you know fathai95 have the first SHINY pet? Wow",
    

  ];