export const randomChats = [
    "POGGERS look at that",
    "Thats nice Ok",
    "LUL",
    "YEP",
    "KEKW",
    "Stare",
    "gachiBASS Boner here i come",
    "Concerned u sure?",
    "Concerned i mean...",
    "boobaPls",
    "CAUGHTIN4K",
    "hyperLick",
    "LOser another one",
    "NOPERS i dont think so",
    "NODDERS damn right",
    "Ok good enough",
    "Lmao look at this guy KEKW",
    "Pog",
    "Talking keep talking",
    "Wow",
    "classic",
    "NOTED uh huh",
    "Plotge",
    "Susge",
    "owojam dance with me owojam",
    "Sussy",
    "you're so right cowsep",
    "Damn bro Wow",
    "Imagine doing that, wouldnt be me Clueless",
    "Hmm interesting",
    "owo",
    "owoshy",
    "pepePoint look guys",
    "Chatting keep typing bud",
    "HUH uhhhh",
    "owoCheer lets go",
    "Shruge idk man",
    "COPIUM good stuff",
    "Aware oh...",
    "COPIUM if you say so...",
    "weSmart smart",
    "fricc you",
    "KEKW Sez u",
    "Concerned You called?",
    "What you gonna do about it Stare",
    "HUH",
    "I kinda agree with that",
    "idk, you tell me buddy KEKW",
    "Pog the skills",
    "peepoCheer pepeD peepoCheer",
  ];